export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOGIN_PATIENT_SUCCESS = 'LOGIN_PATIENT_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOAD_PATIENT_INFO_WITH_UMS_LIST_SUCCESS = 'LOAD_PATIENT_INFO_WITH_UMS_LIST_SUCCESS';
export const LOAD_PATIENT_INFO_WITH_UMS_LIST_NOT_FOUND = 'LOAD_PATIENT_INFO_WITH_UMS_LIST_NOT_FOUND';